
// ignore_for_file: non_constant_identifier_names
part of httper;

/// 
@JsonSerializable()
class FragmentsMoveDto extends BaseObject{

    /// 
    List<RFragment2FragmentGroup> r_fragment_2_fragment_groups_list;

    /// 填充字段1
    bool? dto_padding_1;


FragmentsMoveDto({

    required this.r_fragment_2_fragment_groups_list,

    required this.dto_padding_1,

});
  factory FragmentsMoveDto.fromJson(Map<String, dynamic> json) => _$FragmentsMoveDtoFromJson(json);
    
  @override
  Map<String, dynamic> toJson() => _$FragmentsMoveDtoToJson(this);
  
  
          
  @JsonKey(ignore: true)
  int? code;

  @JsonKey(ignore: true)
  HttperException? httperException;
  
  @JsonKey(ignore: true)
  StackTrace? st;

  @JsonKey(ignore: true)
  FragmentsMoveVo? vo;

  /// 内部抛出的异常将在 [otherException] 中捕获。
  Future<T> handleCode<T>({
    // code 为 null 时的异常（request 函数内部捕获到的异常）
    Future<T> Function(int? code, HttperException httperException, StackTrace st)? otherException,

    // message: 移动成功！
    // explain: 移动碎片。主要对 r 进行修改。需在前端对 r 进行修改，在后端直接save
    required Future<T> Function(String showMessage) code150601,
    
    }) async {
    try {

        if (code == 150601) return await code150601(httperException!.showMessage);

    } catch (handleE, handleSt) {
      if (otherException == null) {
        if (httperException != null) {
          throw httperException!;
        }
        rethrow;
      }
      if (httperException != null) {
        return await otherException(code, httperException!, st!);
      }
      if (handleE is HttperException) {
        return await otherException(code, handleE, handleSt);
      }
      return await otherException(code, HttperException(showMessage: '请求异常！', debugMessage: handleE.toString()), handleSt);
    }
    // 当以流的形式响应时，下面代码被忽略。
    if (code != null) {
      if(otherException==null) throw HttperException(showMessage: '请求异常！', debugMessage: '响应码 $code 未处理！');
      return await otherException(code, HttperException(showMessage: '请求异常！', debugMessage: '响应码 $code 未处理！'), st!);
    }
    if(otherException==null) throw httperException!;
    return await otherException(code, httperException!, st!);
  }
}
